wavelength = 800 * 1e-9;

baseFrequency = 40 * 1e6;
acceptanceAngle = 4.35 * 1e-3; % rad

systemClockFreq = 240e6;
dataTimeInterval = 1 / 20e6;
zoomInteger = 1;

xyElements = 100;
zElements = 1;

dwellTimeMultiplier = 1;
xCentre = 0; 
yCentre = 0; 
zCentre = 0;

[a, b, c, tRamp] = aod_dev_script(...
    xyElements,...
    zElements,...
    acceptanceAngle,...
    dwellTimeMultiplier,...
    wavelength,...
    zoomInteger,...
    baseFrequency,...
    xCentre,...
    yCentre,...
    zCentre,...
    systemClockFreq);
    

